http://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

### Tensors

In [1]:
from __future__ import print_function
import torch

In [2]:
# Construct a 5x3 matrix, uninitialized
x = torch.Tensor(5, 3)
print(x)


1.00000e-22 *
  0.0000  0.0000 -0.0000
  0.0000 -0.0000  0.0000
 -1.5997  0.0000 -1.5997
  0.0000 -1.8747  0.0000
 -1.8293  0.0000 -0.0000
[torch.FloatTensor of size 5x3]



In [3]:
# Construct a randomly initialized matrix
x = torch.rand(5, 3)
print(x)


 0.8407  0.9747  0.9045
 0.0126  0.8773  0.1005
 0.7924  0.6176  0.8439
 0.7790  0.3420  0.4159
 0.1509  0.8036  0.7602
[torch.FloatTensor of size 5x3]



In [4]:
# Get its size
print(x.size())

torch.Size([5, 3])


### Operations

In [5]:
# Addition: syntax 1
y = torch.rand(5, 3)
print(x + y)


 1.7694  1.6942  1.5102
 0.6411  1.5457  0.3096
 1.5303  0.7785  1.8434
 1.0329  0.5154  0.6141
 0.9584  0.8720  1.0317
[torch.FloatTensor of size 5x3]



In [7]:
# Addition: syntax 2
print(torch.add(x, y))


 1.7694  1.6942  1.5102
 0.6411  1.5457  0.3096
 1.5303  0.7785  1.8434
 1.0329  0.5154  0.6141
 0.9584  0.8720  1.0317
[torch.FloatTensor of size 5x3]



In [8]:
# Addition: giving an output tensor
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.7694  1.6942  1.5102
 0.6411  1.5457  0.3096
 1.5303  0.7785  1.8434
 1.0329  0.5154  0.6141
 0.9584  0.8720  1.0317
[torch.FloatTensor of size 5x3]



In [10]:
# Addition: in-place
# adds x to y
y.add_(x)
print(y)


 1.7694  1.6942  1.5102
 0.6411  1.5457  0.3096
 1.5303  0.7785  1.8434
 1.0329  0.5154  0.6141
 0.9584  0.8720  1.0317
[torch.FloatTensor of size 5x3]



In [13]:
# numpy-like indexing
print(y[:, 1])
print(y[-1,-1])


 1.6942
 1.5457
 0.7785
 0.5154
 0.8720
[torch.FloatTensor of size 5]

1.031680703163147


100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here: http://pytorch.org/docs/torch

### Numpy Bridge
Converting a torch Tensor to a numpy array and vice versa.

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [17]:
# Converting torch Tensor to numpy Array
a = torch.ones(5)
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [20]:
# See how the numpy array changed in value.
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [23]:
# numpy Array to torch Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



### CUDA Tensors

In [22]:
# Tensors can be moved onto GPU using the .cuda function.
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    print(x + y)


 2.6100  2.6689  2.4147
 0.6538  2.4230  0.4101
 2.3227  1.3960  2.6873
 1.8119  0.8573  1.0300
 1.1094  1.6756  1.7919
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]



### Autograd: automatic differentiation
http://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#sphx-glr-beginner-blitz-autograd-tutorial-py

"autograd" package
"autograd.Variable": wraps a Tensor, you can call .backward() and have all the gradients computed automatically.

access the raw tensor through the .data attribute, while the gradient w.r.t. this variable is accumulated into .grad.

In [1]:
import torch
from torch.autograd import Variable

In [2]:
# Create a variable:
x = Variable(torch.ones(2, 2), requires_grad=True)
print(x)

Variable containing:
 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [3]:
x.data


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [5]:
# Do an operation of variable:
y = x + 2
print(y)

Variable containing:
 3  3
 3  3
[torch.FloatTensor of size 2x2]



In [9]:
# y was created as a result of an operation, so it has a creator. Through ".creator", know which function is applied.
print(y.creator)

In [7]:
# Do more operations on y
z = y * y * 3
out = z.mean()

print(z, out)

Variable containing:
 27  27
 27  27
[torch.FloatTensor of size 2x2]
 Variable containing:
 27
[torch.FloatTensor of size 1]



In [8]:
out.creator

### Gradients
If you want to compute the derivatives, you can call .backward() on a Variable.

let’s backprop now out.backward() is equivalent to doing out.backward(torch.Tensor([1.0]))

In [10]:
out.backward()

In [11]:
# print gradients d(out)/dx
print(x.grad)

Variable containing:
 4.5000  4.5000
 4.5000  4.5000
[torch.FloatTensor of size 2x2]



In [17]:
# do many crazy things with autograd
x = torch.randn(3)
x = Variable(x, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

Variable containing:
   78.7655
-1088.9884
  165.2964
[torch.FloatTensor of size 3]



In [18]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)

In [19]:
print(x.grad)

Variable containing:
  51.2000
 512.0000
   0.0512
[torch.FloatTensor of size 3]



In [20]:
gradients = torch.FloatTensor([1.1, -1.0, 0.01])
y.backward(gradients)
print(x.grad)

Variable containing:
 614.4000
   0.0000
   5.1712
[torch.FloatTensor of size 3]

