http://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

### Tensors

In [1]:
from __future__ import print_function
import torch

In [2]:
# Construct a 5x3 matrix, uninitialized
x = torch.Tensor(5, 3)
print(x)


1.00000e-22 *
  0.0000  0.0000 -0.0000
  0.0000 -0.0000  0.0000
 -1.5997  0.0000 -1.5997
  0.0000 -1.8747  0.0000
 -1.8293  0.0000 -0.0000
[torch.FloatTensor of size 5x3]



In [3]:
# Construct a randomly initialized matrix
x = torch.rand(5, 3)
print(x)


 0.8407  0.9747  0.9045
 0.0126  0.8773  0.1005
 0.7924  0.6176  0.8439
 0.7790  0.3420  0.4159
 0.1509  0.8036  0.7602
[torch.FloatTensor of size 5x3]



In [4]:
# Get its size
print(x.size())

torch.Size([5, 3])


### Operations

In [5]:
# Addition: syntax 1
y = torch.rand(5, 3)
print(x + y)


 1.7694  1.6942  1.5102
 0.6411  1.5457  0.3096
 1.5303  0.7785  1.8434
 1.0329  0.5154  0.6141
 0.9584  0.8720  1.0317
[torch.FloatTensor of size 5x3]



In [7]:
# Addition: syntax 2
print(torch.add(x, y))


 1.7694  1.6942  1.5102
 0.6411  1.5457  0.3096
 1.5303  0.7785  1.8434
 1.0329  0.5154  0.6141
 0.9584  0.8720  1.0317
[torch.FloatTensor of size 5x3]



In [8]:
# Addition: giving an output tensor
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 1.7694  1.6942  1.5102
 0.6411  1.5457  0.3096
 1.5303  0.7785  1.8434
 1.0329  0.5154  0.6141
 0.9584  0.8720  1.0317
[torch.FloatTensor of size 5x3]



In [10]:
# Addition: in-place
# adds x to y
y.add_(x)
print(y)


 1.7694  1.6942  1.5102
 0.6411  1.5457  0.3096
 1.5303  0.7785  1.8434
 1.0329  0.5154  0.6141
 0.9584  0.8720  1.0317
[torch.FloatTensor of size 5x3]



In [13]:
# numpy-like indexing
print(y[:, 1])
print(y[-1,-1])


 1.6942
 1.5457
 0.7785
 0.5154
 0.8720
[torch.FloatTensor of size 5]

1.031680703163147


100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here: http://pytorch.org/docs/torch

### Numpy Bridge
Converting a torch Tensor to a numpy array and vice versa.

All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

In [17]:
# Converting torch Tensor to numpy Array
a = torch.ones(5)
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [20]:
# See how the numpy array changed in value.
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


In [23]:
# numpy Array to torch Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



### CUDA Tensors

In [22]:
# Tensors can be moved onto GPU using the .cuda function.
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    print(x + y)


 2.6100  2.6689  2.4147
 0.6538  2.4230  0.4101
 2.3227  1.3960  2.6873
 1.8119  0.8573  1.0300
 1.1094  1.6756  1.7919
[torch.cuda.FloatTensor of size 5x3 (GPU 0)]



### Autograd: automatic differentiation
http://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html#sphx-glr-beginner-blitz-autograd-tutorial-py